baseurl: /dongzhidong.github.io
markdown: redcarpet
redcarpet:
    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]
safe: false
pygments: true
excerpt_separator: "\n\n\n"
paginate: 3
paginate_path: "page:num"
