baseurl: /dongzhidong.github.io
markdown: redcarpet
extensions: [ "hard_wrap", "autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify", "no_intra_emphasis"]
permalink: pretty
highlighter: pygments
safe: false
pygments: true
excerpt_separator: "\n\n\n"
paginate: 5
paginate_path: "page:num"
